package com.adriano.cartoon.restclients.responses;

public enum  AutoCompleteResponseStatus {
    AUTOCOMPLETE_SERVICE_INVALID_ARGS,
    AUTOCOMPLETE_SERVICE_NOT_AVAILABLE,
    AUTOCOMPLETE_SERVICE_ERROR,
    AUTOCOMPLETE_SERVICE_OK,
    AUTOCOMPLETE_SERVICE_NO_RESULTS,
    AUTOCOMPLETE_SERVICE_QUOTA_REACHED

}
