package com.adriano.cartoon.restclients.responses;

public enum DirectionsResponseStatus {
    DIRECTIONS_RESPONSE_OK,
    DIRECTIONS_RESPONSE_ERROR,
    DIRECTIONS_RESPONSE_INVALID_ARGS,
    DIRECTIONS_RESPONSE_SERVICE_NOT_AVAILABLE,
    DIRECTIONS_RESPONSE_ROUTE_NOT_FOUND,
    DIRECTIONS_RESPONSE_GEOCODE_FAILED,
    DIRECTIONS_RESPONSE_ROUTE_TOO_LONG
}
