package com.adriano.cartoon.restclients.responses;

public enum GeocodeResponseStatus {
    GEOCODER_SERVICE_INVALID_ARGS,
    GEOCODER_SERVICE_NOT_AVAILABLE,
    GEOCODER_SERVICE_ERROR,
    GEOCODER_SERVICE_OK,
    GEOCODER_SERVICE_NO_RESULTS,
    GEOCODER_SERVICE_QUOTA_REACHED
}
